export const challenges=[
  {
    id:1,
    title:"Tech conference site",
    classRange:"",
    img:"",
    technologies:"",
    premium:"",
  },
  {
    id:2,
    title:"Savings tracker",
    classRange:"",
    img:"",
    technologies:"",
    premium:"",
  },
  {
    id:3,
    title:"Skills learning tracker",
    classRange:"",
    img:"",
    technologies:"",
    premium:"",
  },
  {
    id:4,
    title:"Personal reading list",
    classRange:"",
    img:"",
    technologies:"",
    premium:"",
  },
  {
    id:5,
    title:"RSS feed reader",
    classRange:"",
    img:"",
    technologies:"",
    premium:"",
  },
  {
    id:6,
    title:"Typing speed test",
    classRange:"",
    img:"",
    technologies:"",
    premium:"",
  },
  {
    id:7,
    title:"Flashcard app",
    classRange:"",
    img:"",
    technologies:"",
    premium:"",
  },
  {
    id:8,
    title:"Bookmark manager app",
    classRange:"",
    img:"",
    technologies:"",
    premium:"",
  },
  {
    id:9,
    title:"Weather app",
    classRange:"",
    img:"",
    technologies:"",
    premium:"",
  },
  {
    id:10,
    title:"Recipe finder website",
    classRange:"",
    img:"",
    technologies:"",
    premium:"",
  },
  {
    id:11,
    title:"Mood tracking app",
    classRange:"",
    img:"",
    technologies:"",
    premium:"",
  },


]