export const challenges=[
  {
    id:1,
    title:"Tech conference site",
    classRange:"INTERMEDITE",
    img:"hjlyatjbe8srrohaot1v.webp",
    technologies:["HTML", "CSS","JS"],
    text:"Build a multi-page site for a tech conference. Browse the speakers, filter the schedule by day and track, and save talks. Optional bonus: pull the content from a CMS.",
  },
  {
    id:2,
    title:"Savings tracker",
    classRange:"INTERMEDITE",
    img:"bc16fxcewibkkfwfznu1.webp",
    technologies:["HTML", "CSS","JS"],
    text:"Build a savings tracker app with goal management, deposit tracking, progress visualization, and filtering. Includes optional full-stack auth screens.",
  },
  {
    id:3,
    title:"Skills learning tracker",
    classRange:"INTERMEDITE",
    img:"piecqpk9ovggeeg40ruc.webp",
    technologies:["HTML", "CSS","JS"],
    text:"Build a skills-learning tracker that lets users log practice sessions, track streaks, and visualize their consistency with heatmaps and progress rings.",
  },
  {
    id:4,
    title:"Personal reading list",
    classRange:"advanced",
    img:"llk4mwgpzxoe4vbzcsxd.webp",
    technologies:["HTML", "CSS","JS","API"],
    text:"Build a personal reading list app that lets users search for books, organize them into shelves, track reading progress, and explore year-in-review statistics.",
  },
  {
    id:5,
    title:"RSS feed reader",
    classRange:"advanced",
    img:"gufhpgjkmrme4qtvalak.webp",
    technologies:["HTML", "CSS","JS"],
    text:"Build an RSS feed reader that lets users subscribe to blogs and news sources, organize feeds into categories, and browse articles in a unified timeline.",
  },
  {
    id:6,
    title:"Typing speed test",
    classRange:"JUNIOR",
    img:"evbz8invcnftebjuer3f.webp",
    technologies:["HTML", "CSS","JS"],
    text:"Build a typing speed test that calculates words per minute (WPM) and accuracy. A fun project to practice DOM manipulation and working with timers.",
  },
  {
    id:7,
    title:"Flashcard app",
    classRange:"intermediate",
    img:"xj6kfwu0kgx1cuxmg3v9.webp",
    technologies:["HTML", "CSS","JS"],
    text:"Practice building interactive UI with this flashcard app. Features card flip animations, progress tracking, filtering, and study statistics.",
  },
  {
    id:8,
    title:"Bookmark manager app",
    classRange:"",
    img:"hxtjlnh6jlppaxg4uqsf.webp",
    technologies:"",
    text:"Build a fully-functional bookmark manager with add, edit, archive, search, and filter features. Perfect for practicing forms and state management.",
  },
  {
    id:9,
    title:"Weather app",
    classRange:"ADvanced",
    img:"gufhpgjkmrme4qtvalak.webp",
    technologies:["HTML", "CSS","JS"],
    text:"Build a responsive weather app with search functionality, unit conversion, and detailed forecasts using the Open-Meteo API.",
  },
  {
    id:10,
    title:"Recipe finder website",
    classRange:"ADvanced",
    img:"INTERMEDITE",
    technologies:["HTML", "CSS","JS","API"],
    text:"Build a responsive recipe finder with search, filtering, and dynamic content. Practice working with JSON data, complex layouts, and interactive JavaScript features.",
  },
  {
    id:11,
    title:"Mood tracking app",
    classRange:"ADVANCED",
    img:"ygk0ltusrxjjp9dkxhab.webp",
    technologies:["HTML", "CSS","JS","API"],
    text:"Building this app will be a fun way to test a range of your skills. From working with JSON data to logging and charting mood entries, there's a lot to get stuck into!",
  }


]